{
  "language": "node_js",
  "sudo": true,
  "node_js": "v6.2.2",
  "install": "npm install",
  "cache": {
    "directories": null
  },
  "before_script": [
    "npm install -g json-server",
    "json-server data.json &"
  ],
  "script": [
    "npm test"
  ],
  "after_success": null,
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}